CREATE TABLE IF NOT EXISTS users(
id INTEGER PRIMARY KEY,
username TEXT,
password TEXT
);

CREATE TABLE IF NOT EXISTS games(
id INTEGER PRIMARY KEY,
datePlayed TEXT,
duration INTEGER
);

CREATE TABLE IF NOT EXISTS teams(
id INTEGER PRIMARY KEY,
gameId INTEGER,
score INTEGER
);

CREATE TABLE IF NOT EXISTS particpations(
playerId INTEGER,
teamId INTEGER,
PRIMARY KEY (playerID,teamID),
FOREIGN KEY (playerID) REFERENCES users(id),
FOREIGN KEY (teamId) REFERENCES teams(id)
);